config:
  DelayTime: 20
item:
  ACACIA_DOOR: 合欢木门
  ACACIA_DOOR_ITEM: 合欢木门
  ACACIA_FENCE: 合欢木栅栏
  ACACIA_FENCE_GATE: 合欢木栅栏门
  ACACIA_STAIRS: 合欢木楼梯
  ACTIVATOR_RAIL: 激活铁轨
  AIR: 空气
  ANVIL: 铁砧
  APPLE: 小苹果
  ARMOR_STAND: 盔甲架
  ARROW: 弓箭
  BAKED_POTATO: 烤土豆
  BANNER: 旗帜
  BARRIER: 屏障
  BEACON: 信标
  BED: 床
  BED_BLOCK: 床方块
  BEDROCK: 基岩
  BEETROOT: 甜菜根
  BEETROOT_BLOCK: 甜菜根
  BEETROOT_SEEDS: 甜菜种子
  BEETROOT_SOUP: 甜菜汤
  BIRCH_DOOR: 桦木门
  BIRCH_DOOR_ITEM: 桦木门
  BIRCH_FENCE: 桦木栅栏
  BIRCH_FENCE_GATE: 桦木栅栏门
  BIRCH_WOOD_STAIRS: 桦木楼梯
  BLACK_GLAZED_TERRACOTTA: 黑色带釉陶瓦
  BLACK_SHULKER_BOX: 黑色潜影盒
  BLAZE_POWDER: 烈焰粉
  BLAZE_ROD: 烈焰棒
  BLUE_GLAZED_TERRACOTTA: 蓝色带釉陶瓦
  BLUE_SHULKER_BOX: 蓝色潜影盒
  BOAT: 船
  BOAT_ACACIA: 金合欢木船
  BOAT_BIRCH: 白桦木船
  BOAT_DARK_OAK: 深色橡木船
  BOAT_JUNGLE: 丛林木船
  BOAT_SPRUCE: 云杉木船
  BONE: 骨头
  BONE_BLOCK: 骨头
  BOOK: 书
  BOOK_AND_QUILL: 书和笔
  BOOKSHELF: 书架
  BOW: 弓
  BOWL: 碗
  BREAD: 面包
  BREWING_STAND: 酿造台
  BREWING_STAND_ITEM: 酿造台
  BRICK: 红砖
  BRICK_STAIRS: 红砖楼梯
  BROWN_GLAZED_TERRACOTTA: 棕色带釉陶瓦
  BROWN_MUSHROOM: 棕色蘑菇
  BROWN_SHULKER_BOX: 棕色潜影盒
  BUCKET: 桶
  BURNING_FURNACE: 燃烧的熔炉
  CACTUS: 仙人掌
  CAKE: 蛋糕
  CAKE_BLOCK: 蛋糕
  CARPET: 地毯
  CARROT: 萝卜
  CARROT_ITEM: 萝卜
  CARROT_STICK: 萝卜吊杆
  CAULDRON: 炼药锅
  CAULDRON_ITEM: 炼药锅
  CHAINMAIL_BOOTS: 锁链靴子
  CHAINMAIL_CHESTPLATE: 锁链胸甲
  CHAINMAIL_HELMET: 锁链头盔
  CHAINMAIL_LEGGINGS: 锁链护腿
  CHEST: 箱子
  CHORUS_FLOWER: 紫颂花
  CHORUS_FRUIT: 紫颂果
  CHORUS_FRUIT_POPPED: 爆裂紫颂果
  CHORUS_PLANT: 紫颂植物
  CLAY: 粘土
  CLAY_BALL: 粘土球
  CLAY_BRICK: 粘土砖
  COAL: 煤
  COAL_BLOCK: 煤块
  COAL_ORE: 煤矿
  COBBLE_WALL: 圆石墙
  COBBLESTONE: 圆石
  COBBLESTONE_STAIRS: 圆石楼梯
  COCOA: 可可
  COMMAND: 命令方块
  COMMAND_CHAIN: 连锁型命令方块
  COMMAND_MINECART: 命令方块矿车
  COMMAND_REPEATING: 循环型命令方块
  COMPASS: 指南针
  CONCRETE: 混凝土
  CONCRETE_POWDER: 混凝土粉末
  COOKED_BEEF: 熟牛排
  COOKED_CHICKEN: 熟鸡排
  COOKED_FISH: 熟鱼
  COOKED_MUTTON: 熟羊肉
  COOKED_RABBIT: 熟兔肉
  COOKIE: 饼干
  CROPS: 作物
  CYAN_GLAZED_TERRACOTTA: 青色带釉陶瓦
  CYAN_SHULKER_BOX: 青色潜影盒
  DARK_OAK_DOOR: 深色橡木门
  DARK_OAK_DOOR_ITEM: 深色橡木门
  DARK_OAK_FENCE: 深色橡木栅栏
  DARK_OAK_FENCE_GATE: 深色橡木栅栏门
  DARK_OAK_STAIRS: 深色橡木楼梯
  DAYLIGHT_DETECTOR: 阳光传感器
  DAYLIGHT_DETECTOR_INVERTED: 阳光传感器
  DEAD_BUSH: 枯死的灌木
  DETECTOR_RAIL: 探测铁轨
  DIAMOND: 大钻石
  DIAMOND_AXE: 土豪专用钻石斧
  DIAMOND_BARDING: 土豪专用钻石鞍
  DIAMOND_BLOCK: 钻石块
  DIAMOND_BOOTS: 土豪专用钻石靴
  DIAMOND_CHESTPLATE: 土豪专用钻石胸甲
  DIAMOND_HELMET: 土豪专用钻石头盔
  DIAMOND_HOE: 土豪专用钻石出头
  DIAMOND_LEGGINGS: 土豪专用钻石护腿
  DIAMOND_ORE: 钻石矿
  DIAMOND_PICKAXE: 土豪专用钻石镐
  DIAMOND_SPADE: 土豪专用钻石铲
  DIAMOND_SWORD: 土豪专用钻石剑
  DIODE: 红石中继器
  DIODE_BLOCK_OFF: 红石中继器(关)
  DIODE_BLOCK_ON: 红石中继器(开)
  DIRT: 土
  DISPENSER: 发射器
  DOUBLE_PLANT: 植物
  DOUBLE_STEP: 台阶
  DOUBLE_STONE_SLAB2: 双红砂岩台阶
  DRAGON_EGG: 龙蛋
  DRAGONS_BREATH: 龙息
  DROPPER: 投掷器
  EGG: 蛋蛋
  ELYTRA: 鞘翅
  EMERALD: 绿宝石
  EMERALD_BLOCK: 绿宝石块
  EMERALD_ORE: 绿宝石矿
  EMPTY_MAP: 空地图
  ENCHANTED_BOOK: 附魔书
  ENCHANTMENT_TABLE: 附魔台
  END_BRICKS: 末地石砖
  END_CRYSTAL: 末地水晶
  END_GATEWAY: 
  END_ROD: 末地烛
  ENDER_CHEST: 末影箱
  ENDER_PEARL: 末影珍珠
  ENDER_PORTAL: 末影传送门
  ENDER_PORTAL_FRAME: 末影传送门框
  ENDER_STONE: 末影石
  EXP_BOTTLE: 经验瓶
  EXPLOSIVE_MINECART: 爆炸矿车
  EYE_OF_ENDER: 末影之眼
  FEATHER: 羽毛
  FENCE: 栅栏
  FENCE_GATE: 栅栏门
  FERMENTED_SPIDER_EYE: 发酵的蜘蛛眼
  FIRE: 火
  FIREBALL: 火焰弹
  FIREWORK: 烟花
  FIREWORK_CHARGE: 发射的烟花
  FISHING_ROD: 钓鱼竿
  FLINT: 燧石
  FLINT_AND_STEEL: 打火石
  FLOWER_POT: 花盆
  FLOWER_POT_ITEM: 花盆
  FROSTED_ICE: 霜冰
  FURNACE: 炉子
  GHAST_TEAR: 恶魂之泪
  GLASS: 玻璃
  GLASS_BOTTLE: 玻璃瓶
  GLOWING_REDSTONE_ORE: 红石矿
  GLOWSTONE: 荧石
  GLOWSTONE_DUST: 荧石粉
  GOLD_AXE: 伪土豪专用金斧头
  GOLD_BARDING: 伪土豪专用金马甲
  GOLD_BLOCK: 金块
  GOLD_BOOTS: 伪土豪专用金靴子
  GOLD_CHESTPLATE: 伪土豪专用金胸甲
  GOLD_HELMET: 伪土豪专用金头盔
  GOLD_HOE: 伪土豪专用金锄头
  GOLD_INGOT: 金锭
  GOLD_LEGGINGS: 伪土豪专用金护腿
  GOLD_NUGGET: 金粒
  GOLD_ORE: 金矿
  GOLD_PICKAXE: 伪土豪专用金镐
  GOLD_PLATE: 伪土豪专用金板
  GOLD_RECORD: 金色唱片
  GOLD_SPADE: 伪土豪专用金铲
  GOLD_SWORD: 伪土豪专用金剑
  GOLDEN_APPLE: 金小苹果
  GOLDEN_CARROT: 金萝卜
  GRASS: 草
  GRASS_PATH: 草径
  GRAVEL: 砂砾
  GRAY_GLAZED_TERRACOTTA: 灰色带釉陶瓦
  GRAY_SHULKER_BOX: 灰色潜影盒
  GREEN_GLAZED_TERRACOTTA: 绿色带釉陶瓦
  GREEN_RECORD: 绿色唱片
  GREEN_SHULKER_BOX: 绿色潜影盒
  GRILLED_PORK: 烟花
  HARD_CLAY: 硬质粘土
  HAY_BLOCK: 干草块
  HOPPER: 漏斗
  HOPPER_MINECART: 漏斗
  HUGE_MUSHROOM_1: 大蘑菇1号
  HUGE_MUSHROOM_2: 大蘑菇2号
  ICE: 冰
  INK_SACK: 
  IRON_AXE: 铁斧
  IRON_BARDING: 铁马铠
  IRON_BLOCK: 铁块
  IRON_BOOTS: 铁靴
  IRON_CHESTPLATE: 铁胸甲
  IRON_DOOR: 铁门
  IRON_DOOR_BLOCK: 铁门
  IRON_FENCE: 铁炉
  IRON_HELMET: 铁头盔
  IRON_HOE: 铁锄
  IRON_INGOT: 铁锭
  IRON_LEGGINGS: 铁护腿
  IRON_NUGGET: 铁粒
  IRON_ORE: 铁矿
  IRON_PICKAXE: 铁镐
  IRON_PLATE: 铁板
  IRON_SPADE: 铁铲
  IRON_SWORD: 铁剑
  IRON_TRAPDOOR: 铁活板门
  ITEM_FRAME: 物品展示框
  JACK_O_LANTERN: 南瓜灯
  JUKEBOX: 音乐盒
  JUNGLE_DOOR: 丛林木门
  JUNGLE_DOOR_ITEM: 丛林木门
  JUNGLE_FENCE: 丛林木栅栏
  JUNGLE_FENCE_GATE: 丛林木栅栏门
  JUNGLE_WOOD_STAIRS: 丛林木楼梯
  KNOWLEDGE_BOOK: 知识之书
  LADDER: 梯子
  LAPIS_BLOCK: 青金石块
  LAPIS_ORE: 青金石矿
  LAVA: 岩浆
  LAVA_BUCKET: 岩浆桶
  LEASH: 栓绳
  LEATHER: 皮革
  LEATHER_BOOTS: 皮靴
  LEATHER_CHESTPLATE: 皮胸甲
  LEATHER_HELMET: 皮头盔
  LEATHER_LEGGINGS: 皮护腿
  LEAVES: 叶子
  LEAVES_2: 叶子
  LEVER: 拉杆
  LIGHT_BLUE_GLAZED_TERRACOTTA: 浅蓝色带釉陶瓦
  LIGHT_BLUE_SHULKER_BOX: 浅蓝色潜影盒
  LIME_GLAZED_TERRACOTTA: 青柠色带釉陶瓦
  LIME_SHULKER_BOX: 青柠色潜影盒
  LINGERING_POTION: 滞留药水
  LOG: 木头
  LOG_2: 木头
  LONG_GRASS: 长草
  MAGENTA_GLAZED_TERRACOTTA: 品红色带釉陶瓦
  MAGENTA_SHULKER_BOX: 品红色潜影盒
  MAGMA: 岩浆块
  MAGMA_CREAM: 岩浆膏
  MAP: 地图
  MELON: 西瓜
  MELON_BLOCK: 西瓜
  MELON_SEEDS: 西瓜种子
  MELON_STEM: 西瓜
  MILK_BUCKET: 牛奶桶
  MINECART: 矿车
  MOB_SPAWNER: 刷怪笼
  MONSTER_EGG: 怪物蛋
  MONSTER_EGGS: 怪物蛋(们)
  MOSSY_COBBLESTONE: 苔石
  MUSHROOM_SOUP: 蘑菇汤
  MUTTON: 羊肉
  MYCEL: 菌丝
  NAME_TAG: 姓名版
  NETHER_BRICK: 地狱砖
  NETHER_BRICK_ITEM: 地狱砖
  NETHER_BRICK_STAIRS: 地狱楼梯
  NETHER_FENCE: 地狱栅栏
  NETHER_STALK: 地狱疣
  NETHER_STAR: 下界之星
  NETHER_WART_BLOCK: 地狱疣块
  NETHER_WARTS: 地狱疣
  NETHERRACK: 地狱岩
  NOTE_BLOCK: 音符盒
  OBSERVER: 侦测器
  OBSIDIAN: 黑曜石
  ORANGE_GLAZED_TERRACOTTA: 橙色带釉陶瓦
  ORANGE_SHULKER_BOX: 橙色潜影盒
  PACKED_ICE: 浮冰
  PAINTING: 画
  PAPER: 纸
  PINK_GLAZED_TERRACOTTA: 粉色带釉陶瓦
  PINK_SHULKER_BOX: 粉色潜影盒
  PISTON_BASE: 奇怪的东西
  PISTON_EXTENSION: 奇怪的东西
  PISTON_MOVING_PIECE: 奇怪的东西
  PISTON_STICKY_BASE: 奇怪的东西
  POISONOUS_POTATO: 毒土豆
  PORK: 猪肉
  PORTAL: 传送门
  POTATO: 土豆
  POTATO_ITEM: 土豆
  POTION: 药水
  POWERED_MINECART: 动力矿车
  POWERED_RAIL: 动力铁轨
  PRISMARINE: 海晶石
  PRISMARINE_CRYSTALS: 海晶砂粒
  PRISMARINE_SHARD: 海晶碎片
  PUMPKIN: 南瓜
  PUMPKIN_PIE: 南瓜派
  PUMPKIN_SEEDS: 南瓜种子
  PUMPKIN_STEM: 南瓜
  PURPLE_GLAZED_TERRACOTTA: 紫色带釉陶瓦
  PURPLE_SHULKER_BOX: 紫色潜影盒
  PURPUR_BLOCK: 紫珀块
  PURPUR_DOUBLE_SLAB: 紫珀台阶
  PURPUR_PILLAR: 竖纹紫珀块
  PURPUR_SLAB: 紫珀台阶
  PURPUR_STAIRS: 紫珀楼梯
  QUARTZ: 石英
  QUARTZ_BLOCK: 石英块
  QUARTZ_ORE: 石英矿
  QUARTZ_STAIRS: 石英楼梯
  RABBIT: 兔子
  RABBIT_FOOT: 兔子脚
  RABBIT_HIDE: 兔子皮
  RABBIT_STEW: 兔肉煲
  RAILS: 铁轨
  RAW_BEEF: 生牛肉
  RAW_CHICKEN: 生鸡
  RAW_FISH: 生鱼
  RECORD_10: 唱片
  RECORD_11: 唱片
  RECORD_12: 唱片
  RECORD_3: 唱片
  RECORD_4: 唱片
  RECORD_5: 唱片
  RECORD_6: 唱片
  RECORD_7: 唱片
  RECORD_8: 唱片
  RECORD_9: 唱片
  RED_GLAZED_TERRACOTTA: 红色带釉陶瓦
  RED_MUSHROOM: 红蘑菇
  RED_NETHER_BRICK: 红色地狱砖
  RED_ROSE: 红玫瑰
  RED_SANDSTONE: 红砂岩
  RED_SANDSTONE_STAIRS: 红砂岩楼梯
  RED_SHULKER_BOX: 红色潜影盒
  REDSTONE: 红石
  REDSTONE_BLOCK: 红石块
  REDSTONE_COMPARATOR: 红石比较器
  REDSTONE_COMPARATOR_OFF: 红石比较器(关)
  REDSTONE_COMPARATOR_ON: 红石比较器(开)
  REDSTONE_LAMP_OFF: 红石灯(关)
  REDSTONE_LAMP_ON: 红石灯(开)
  REDSTONE_ORE: 红石矿
  REDSTONE_TORCH_OFF: 红石火把(关)
  REDSTONE_TORCH_ON: 红石火把(开)
  REDSTONE_WIRE: 红石导线
  ROTTEN_FLESH: 腐肉
  SADDLE: 鞍
  SAND: 沙子
  SANDSTONE: 砂石
  SANDSTONE_STAIRS: 砂石楼梯
  SAPLING: 树苗
  SEA_LANTERN: 海晶灯
  SEEDS: 种子
  SHEARS: 剪刀
  SHIELD: 盾牌
  SHULKER_SHELL: 潜影壳
  SIGN: 告示牌
  SIGN_POST: 告示牌
  SILVER_GLAZED_TERRACOTTA: 淡灰色带釉陶瓦
  SILVER_SHULKER_BOX: 淡灰色潜影盒
  SKULL: 骷髅
  SKULL_ITEM: 骷髅
  SLIME_BALL: 粘液球
  SLIME_BLOCK: 粘液块
  SMOOTH_BRICK: 石砖
  SMOOTH_STAIRS: 石砖楼梯
  SNOW: 雪
  SNOW_BALL: 雪球
  SNOW_BLOCK: 雪块
  SOIL: 土
  SOUL_SAND: 灵魂沙
  SPECKLED_MELON: 闪烁的西瓜
  SPECTRAL_ARROW: 光灵箭
  SPIDER_EYE: 蜘蛛眼
  SPLASH_POTION: 喷溅药水
  SPONGE: 海绵
  SPRUCE_DOOR: 云杉木门
  SPRUCE_DOOR_ITEM: 云杉木门
  SPRUCE_FENCE: 云杉木栅栏
  SPRUCE_FENCE_GATE: 云杉木栅栏门
  SPRUCE_WOOD_STAIRS: 云杉木楼梯
  STAINED_CLAY: 染色粘土
  STAINED_GLASS: 染色玻璃
  STAINED_GLASS_PANE: 染色玻璃板
  STANDING_BANNER: 
  STATIONARY_LAVA: 平稳的岩浆
  STATIONARY_WATER: 平稳的水
  STEP: 台阶
  STICK: 木棍
  STONE: 石头
  STONE_AXE: 石斧
  STONE_BUTTON: 石头按钮
  STONE_HOE: 石锄
  STONE_PICKAXE: 石镐
  STONE_PLATE: 石板
  STONE_SLAB2: 石台阶
  STONE_SPADE: 石铲
  STONE_SWORD: 石剑
  STORAGE_MINECART: 运输矿车
  STRING: 线
  STRUCTURE_BLOCK: 结构方块
  STRUCTURE_VOID: 结构空位
  SUGAR: 糖
  SUGAR_CANE: 甘蔗
  SUGAR_CANE_BLOCK: 甘蔗
  SULPHUR: 火药
  THIN_GLASS: 玻璃板
  TIPPED_ARROW: 药箭
  TNT: TNT
  TORCH: 火把
  TOTEM: 不死图腾
  TRAP_DOOR: 活板门
  TRAPPED_CHEST: 陷阱箱
  TRIPWIRE: 拌线
  TRIPWIRE_HOOK: 拌线钩
  VINE: 藤蔓
  WALL_BANNER: 
  WALL_SIGN: 告示牌
  WATCH: 表
  WATER: 水
  WATER_BUCKET: 水桶
  WATER_LILY: 浮萍
  WEB: 网
  WHEAT: 小麦
  WHITE_GLAZED_TERRACOTTA: 白色带釉陶瓦
  WHITE_SHULKER_BOX: 白色潜影盒
  WOOD: 木头
  WOOD_AXE: 木斧
  WOOD_BUTTON: 木质按钮
  WOOD_DOOR: 木门
  WOOD_DOUBLE_STEP: 木台阶
  WOOD_HOE: 木锄
  WOOD_PICKAXE: 木镐
  WOOD_PLATE: 木板
  WOOD_SPADE: 木铲
  WOOD_STAIRS: 木楼梯
  WOOD_STEP: 木台阶
  WOOD_SWORD: 木剑
  WOODEN_DOOR: 木门
  WOOL: 羊毛
  WORKBENCH: 工作台
  WRITTEN_BOOK: 并不是无字天书的书
  YELLOW_FLOWER: 黄花
  YELLOW_GLAZED_TERRACOTTA: 黄色带釉陶瓦
  YELLOW_SHULKER_BOX: 黄色潜影盒
