config:
    DelayTime: 20
item:
    ACTIVATOR_RAIL: 激活铁轨
    AIR: 空气
    ANVIL: 铁砧
    APPLE: 小苹果
    ARROW: 弓箭
    BAKED_POTATO: 烤土豆
    BEACON: 信标
    BED: 床
    BED_BLOCK: 床方块
    BEDROCK: 基岩
    BIRCH_WOOD_STAIRS: 桦木楼梯
    BLAZE_POWDER: 烈焰粉
    BLAZE_ROD: 烈焰棒
    BOAT: 船
    BONE: 骨头
    BOOK: 书
    BOOK_AND_QUILL: 书和笔
    BOOKSHELF: 书架
    BOW: 弓
    BOWL: 碗
    BREAD: 面包
    BREWING_STAND: 酿造台
    BREWING_STAND_ITEM: 酿造台
    BRICK: 红砖
    BRICK_STAIRS: 红砖楼梯
    BROWN_MUSHROOM: 棕色蘑菇
    BUCKET: 桶
    BURNING_FURNACE: 燃烧的熔炉
    CACTUS: 仙人掌
    CAKE: 蛋糕
    CAKE_BLOCK: 蛋糕
    CARPET: 地毯
    CARROT: 萝卜
    CARROT_ITEM: 萝卜
    CARROT_STICK: 萝卜吊杆
    CAULDRON: 炼药锅
    CAULDRON_ITEM: 炼药锅
    CHAINMAIL_BOOTS: 锁链靴子
    CHAINMAIL_CHESTPLATE: 锁链胸甲
    CHAINMAIL_HELMET: 锁链头盔
    CHAINMAIL_LEGGINGS: 锁链护腿
    CHEST: 箱子
    CLAY: 粘土
    CLAY_BALL: 粘土球
    CLAY_BRICK: 粘土砖
    COAL: 煤
    COAL_BLOCK: 煤块
    COAL_ORE: 煤矿
    COBBLE_WALL: 圆石墙
    COBBLESTONE: 圆石
    COBBLESTONE_STAIRS: 圆石楼梯
    COCOA: 可可
    COMMAND: 命令方块
    COMPASS: 指南针
    COOKED_BEEF: 熟牛肉
    COOKED_CHICKEN: 熟鸡
    COOKED_FISH: 熟鱼
    COOKIE: 饼干
    CROPS: 作物
    DAYLIGHT_DETECTOR: 感光板
    DEAD_BUSH: 枯死的灌木
    DETECTOR_RAIL: 探测铁轨
    DIAMOND: 大钻石
    DIAMOND_AXE: 土豪专用钻石斧
    DIAMOND_BARDING: 土豪专用钻石鞍
    DIAMOND_BLOCK: 钻石块
    DIAMOND_BOOTS: 土豪专用钻石靴
    DIAMOND_CHESTPLATE: 土豪专用钻石胸甲
    DIAMOND_HELMET: 土豪专用钻石头盔
    DIAMOND_HOE: 土豪专用钻石出头
    DIAMOND_LEGGINGS: 土豪专用钻石护腿
    DIAMOND_ORE: 钻石矿
    DIAMOND_PICKAXE: 土豪专用钻石镐
    DIAMOND_SPADE: 土豪专用钻石铲
    DIAMOND_SWORD: 土豪专用钻石剑
    DIODE: 红石中继器
    DIODE_BLOCK_OFF: 红石中继器(关)
    DIODE_BLOCK_ON: 红石中继器(开)
    DIRT: 土
    DISPENSER: 发射器
    DOUBLE_STEP: 台阶
    DRAGON_EGG: 龙蛋
    DROPPER: 投掷器
    EGG: 蛋蛋
    EMERALD: 绿宝石
    EMERALD_BLOCK: 绿宝石块
    EMERALD_ORE: 绿宝石矿
    EMPTY_MAP: 空地图
    ENCHANTED_BOOK: 附魔书
    ENCHANTMENT_TABLE: 附魔台
    ENDER_CHEST: 末影箱
    ENDER_PEARL: 末影珍珠
    ENDER_PORTAL: 末影传送门
    ENDER_PORTAL_FRAME: 末影传送门框
    ENDER_STONE: 末影石
    EXP_BOTTLE: 经验瓶
    EXPLOSIVE_MINECART: 爆炸矿车
    EYE_OF_ENDER: 末影之眼
    FEATHER: 羽毛
    FENCE: 栅栏
    FENCE_GATE: 栅栏门
    FERMENTED_SPIDER_EYE: 发酵的蜘蛛眼
    FIRE: 火
    FIREBALL: 火焰弹
    FIREWORK: 烟花
    FIREWORK_CHARGE: 发射的烟花
    FISHING_ROD: 钓鱼竿
    FLINT: 燧石
    FLINT_AND_STEEL: 打火石
    FLOWER_POT: 花盆
    FLOWER_POT_ITEM: 花盆
    FURNACE: 炉子
    GHAST_TEAR: 恶魂之泪
    GLASS: 玻璃
    GLASS_BOTTLE: 玻璃瓶
    GLOWING_REDSTONE_ORE: 红石矿
    GLOWSTONE: 荧石
    GLOWSTONE_DUST: 荧石粉
    GOLD_AXE: 伪土豪专用金斧头
    GOLD_BARDING: 伪土豪专用金马甲
    GOLD_BLOCK: 金块
    GOLD_BOOTS: 伪土豪专用金靴子
    GOLD_CHESTPLATE: 伪土豪专用金胸甲
    GOLD_HELMET: 伪土豪专用金头盔
    GOLD_HOE: 伪土豪专用金锄头
    GOLD_INGOT: 金锭
    GOLD_LEGGINGS: 伪土豪专用金护腿
    GOLD_NUGGET: 金粒
    GOLD_ORE: 金矿
    GOLD_PICKAXE: 伪土豪专用金镐
    GOLD_PLATE: 伪土豪专用金板
    GOLD_RECORD: 金色唱片
    GOLD_SPADE: 伪土豪专用金铲
    GOLD_SWORD: 伪土豪专用金剑
    GOLDEN_APPLE: 金小苹果
    GOLDEN_CARROT: 金萝卜
    GRASS: 草
    GRAVEL: 砂砾
    GREEN_RECORD: 绿色唱片
    GRILLED_PORK: 烟花
    HARD_CLAY: 硬质粘土
    HAY_BLOCK: 干草块
    HOPPER: 漏斗
    HOPPER_MINECART: 漏斗
    HUGE_MUSHROOM_1: 大蘑菇1号
    HUGE_MUSHROOM_2: 大蘑菇2号
    ICE: 冰
    INK_SACK: 
    IRON_AXE: 铁斧
    IRON_BARDING: 铁马铠
    IRON_BLOCK: 铁块
    IRON_BOOTS: 铁靴
    IRON_CHESTPLATE: 铁胸甲
    IRON_DOOR: 铁门
    IRON_DOOR_BLOCK: 铁门
    IRON_FENCE: 铁炉
    IRON_HELMET: 铁头盔
    IRON_HOE: 铁锄
    IRON_INGOT: 铁锭
    IRON_LEGGINGS: 铁护腿
    IRON_ORE: 铁矿
    IRON_PICKAXE: 铁镐
    IRON_PLATE: 铁板
    IRON_SPADE: 铁铲
    IRON_SWORD: 铁剑
    ITEM_FRAME: 物品展示框
    JACK_O_LANTERN: 南瓜灯
    JUKEBOX: 音乐盒
    JUNGLE_WOOD_STAIRS: 灌木楼梯
    LADDER: 梯子
    LAPIS_BLOCK: 青金石块
    LAPIS_ORE: 青金石矿
    LAVA: 岩浆
    LAVA_BUCKET: 岩浆桶
    LEASH: 栓绳
    LEATHER: 皮革
    LEATHER_BOOTS: 皮靴
    LEATHER_CHESTPLATE: 皮胸甲
    LEATHER_HELMET: 皮头盔
    LEATHER_LEGGINGS: 皮护腿
    LEAVES: 叶子
    LEVER: 拉杆
    LOCKED_CHEST: 上锁的箱子
    LOG: 木头
    LONG_GRASS: 长草
    MAGMA_CREAM: 岩浆膏
    MAP: 地图
    MELON: 西瓜
    MELON_BLOCK: 西瓜
    MELON_SEEDS: 西瓜种子
    MELON_STEM: 西瓜
    MILK_BUCKET: 牛奶桶
    MINECART: 矿车
    MOB_SPAWNER: 刷怪笼
    MONSTER_EGG: 怪物蛋
    MONSTER_EGGS: 怪物蛋(们)
    MOSSY_COBBLESTONE: 苔石
    MUSHROOM_SOUP: 蘑菇汤
    MYCEL: 菌丝
    NAME_TAG: 姓名版
    NETHER_BRICK: 地狱砖
    NETHER_BRICK_ITEM: 地狱砖
    NETHER_BRICK_STAIRS: 地狱楼梯
    NETHER_FENCE: 地狱栅栏
    NETHER_STALK: 地狱疣
    NETHER_STAR: 下界之星
    NETHER_WARTS: 地狱疣
    NETHERRACK: 地狱岩
    NOTE_BLOCK: 音符盒
    OBSIDIAN: 黑曜石
    PAINTING: 画
    PAPER: 纸
    PISTON_BASE: 奇怪的东西
    PISTON_EXTENSION: 奇怪的东西
    PISTON_MOVING_PIECE: 奇怪的东西
    PISTON_STICKY_BASE: 奇怪的东西
    POISONOUS_POTATO: 毒土豆
    PORK: 猪肉
    PORTAL: 传送门
    POTATO: 土豆
    POTATO_ITEM: 土豆
    POTION: 药水
    POWERED_MINECART: 动力矿车
    POWERED_RAIL: 动力铁轨
    PUMPKIN: 南瓜
    PUMPKIN_PIE: 南瓜派
    PUMPKIN_SEEDS: 南瓜种子
    PUMPKIN_STEM: 南瓜
    QUARTZ: 石英
    QUARTZ_BLOCK: 石英块
    QUARTZ_ORE: 石英矿
    QUARTZ_STAIRS: 石英楼梯
    RAILS: 铁轨
    RAW_BEEF: 生牛肉
    RAW_CHICKEN: 生鸡
    RAW_FISH: 生鱼
    RECORD_10: 空
    RECORD_11: 空
    RECORD_12: 空
    RECORD_3: 空
    RECORD_4: 空
    RECORD_5: 空
    RECORD_6: 空
    RECORD_7: 空
    RECORD_8: 空
    RECORD_9: 空
    RED_MUSHROOM: 红蘑菇
    RED_ROSE: 红玫瑰
    REDSTONE: 红石
    REDSTONE_BLOCK: 红石块
    REDSTONE_COMPARATOR: 红石比较器
    REDSTONE_COMPARATOR_OFF: 红石比较器(关)
    REDSTONE_COMPARATOR_ON: 红石比较器(开)
    REDSTONE_LAMP_OFF: 红石灯(关)
    REDSTONE_LAMP_ON: 红石灯(开)
    REDSTONE_ORE: 红石矿
    REDSTONE_TORCH_OFF: 红石火把(关)
    REDSTONE_TORCH_ON: 红石火把(开)
    REDSTONE_WIRE: 红石导线
    ROTTEN_FLESH: 腐肉
    SADDLE: 鞍
    SAND: 沙子
    SANDSTONE: 砂石
    SANDSTONE_STAIRS: 砂石楼梯
    SAPLING: 树苗
    SEEDS: 种子
    SHEARS: 剪刀
    SIGN: 告示牌
    SIGN_POST: 告示牌
    SKULL: 骷髅
    SKULL_ITEM: 骷髅
    SLIME_BALL: 粘液球
    SMOOTH_BRICK: 石砖
    SMOOTH_STAIRS: 石砖楼梯
    SNOW: 雪
    SNOW_BALL: 雪球
    SNOW_BLOCK: 雪块
    SOIL: 土
    SOUL_SAND: 灵魂沙
    SPECKLED_MELON: 闪烁的西瓜
    SPIDER_EYE: 蜘蛛眼
    SPONGE: 海绵
    SPRUCE_WOOD_STAIRS: 云杉木楼梯
    STAINED_CLAY: 硬化粘土
    STATIONARY_LAVA: 平稳的岩浆
    STATIONARY_WATER: 平稳的水
    STEP: 台阶
    STICK: 木棍
    STONE: 石头
    STONE_AXE: 石斧
    STONE_BUTTON: 石头按钮
    STONE_HOE: 石锄
    STONE_PICKAXE: 石镐
    STONE_PLATE: 石板
    STONE_SPADE: 石铲
    STONE_SWORD: 石剑
    STORAGE_MINECART: 运输矿车
    STRING: 线
    SUGAR: 糖
    SUGAR_CANE: 甘蔗
    SUGAR_CANE_BLOCK: 甘蔗
    SULPHUR: 火药
    THIN_GLASS: 玻璃板
    TNT: TNT
    TORCH: 火把
    TRAP_DOOR: 活板门
    TRAPPED_CHEST: 陷阱箱
    TRIPWIRE: 拌线
    TRIPWIRE_HOOK: 拌线钩
    VINE: 藤蔓
    WALL_SIGN: 告示牌
    WATCH: 表
    WATER: 水
    WATER_BUCKET: 水桶
    WATER_LILY: 浮萍
    WEB: 网
    WHEAT: 小麦
    WOOD: 木头
    WOOD_AXE: 木斧
    WOOD_BUTTON: 木质按钮
    WOOD_DOOR: 木门
    WOOD_DOUBLE_STEP: 木台阶
    WOOD_HOE: 木锄
    WOOD_PICKAXE: 木镐
    WOOD_PLATE: 木板
    WOOD_SPADE: 木铲
    WOOD_STAIRS: 木楼梯
    WOOD_STEP: 木台阶
    WOOD_SWORD: 木剑
    WOODEN_DOOR: 木门
    WOOL: 羊毛
    WORKBENCH: 工作台
    WRITTEN_BOOK: 并不是无字天书的书
    YELLOW_FLOWER : 黄花